name: GitHub Actions Demo
run-name: ${{ github.actor }} has pushed new version to repository !
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
# Ak budu testy
#      - run: npm test
