name: 🔧 Build & Test npm
run-name: Push by ${{ github.actor }} has triggered run with ID - ${{ github.run_id }} !
on: [push]
jobs:
  Checkout:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  Install:
    needs: [Checkout]
    runs-on: [self-hosted, linux]
    steps:
      - name: Initialize Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
  Lint:
    needs: [Checkout, Install]
    runs-on: [self-hosted, linux]
    steps:
      - name: Lint using ESLint
        continue-on-error: true
        run: npm run lint
  Build:
    needs: [Checkout, Install]
    runs-on: [self-hosted, linux]
    steps:
      - name: Build with default script
        run: npm run build --if-present
        continue-on-error: true