name: 🔧 Deploy application to GitHub Pages
run-name: Triggered by ${{ github.actor }} with ID - ${{ github.run_id }} !
on: [workflow_dispatch]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
        name: Initialize Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        uses: actions/setup-node@v4
        run: npm ci
      - name: Lint using ESLint
        uses: actions/setup-node@v4
        continue-on-error: true
        run: npm run lint
      - name: Build with default script
        run: npm run build --if-present
        continue-on-error: true
        uses: actions/setup-node@v4
